[package]
name = "also_sync_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
default = ["tokio"]
tokio = []

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"]}
proc-macro2 = "1"
quote = "1"
